export default {
  rules: {
    'require-description': 'error',
    'description-format': ['error', { requireCapitalFirstLetter: true, requireEndingPeriod: true }],
    'require-license': 'error',
    'require-name': 'error',
    'require-repository': 'error',
    'require-version': 'error',
    'require-bugs': 'error',
    'require-homepage': 'error',
    'require-keywords': 'error',
    'no-file-dependencies': 'error',
    'no-file-devDependencies': 'error',
    'no-git-dependencies': 'warning',
    'no-git-devDependencies': 'warning',
    'prefer-alphabetical-dependencies': 'error',
    'prefer-alphabetical-devDependencies': 'error',
    'prefer-alphabetical-peerDependencies': 'error',
    'config-type': 'error',
    'name-format': 'error',
    'version-format': 'error',
    'bin-type': 'error',
    'cpu-type': 'error',
    'dependencies-type': 'error',
    'description-type': 'error',
    'devDependencies-type': 'error',
    'directories-type': 'error',
    'engines-type': 'error',
    'files-type': 'error',
    'homepage-type': 'error',
    'keywords-type': 'error',
    'license-type': 'error',
    'main-type': 'error',
    'man-type': 'error',
    'name-type': 'error',
    'optionalDependencies-type': 'error',
    'os-type': 'error',
    'peerDependencies-type': 'error',
    'preferGlobal-type': 'error',
    'private-type': 'error',
    'repository-type': 'error',
    'scripts-type': 'error',
    'version-type': 'error'
  }
}
